#!/usr/bin/bash
#
# Plugin to monitor the number of vulnerabilities on the machine using
# pkg_admin audit.
#

PKG_ADMIN='/opt/local/sbin/pkg_admin'

echo -n "vulnerabilities.value "
$PKG_ADMIN audit | awk '{ print $2 }' | uniq | wc -l