#!/bin/sh

svcs -a -o state,nstate | awk '
NR > 1 {
        a[$1]++
}
BEGIN {
        a["degraded"]      = 0
        a["disabled"]      = 0
        a["maintenance"]   = 0
        a["offline"]       = 0
        a["online"]        = 0
        a["uninitialized"] = 0
        a["legacy_run"]    = 0
}
END {
        for(k in a) {
                print k ".value", a[k]
        }
}'