#!/usr/bin/bash -e

. /lib/svc/share/smf_include.sh

set -e

case $1 in
	start)
		/opt/local/bin/beaver -c /opt/local/etc/beaver.conf -D -P /var/tmp/beaver.pid -l /var/log/beaver.log
	;;
	stop)
		if [[ -f /var/tmp/beaver.pid ]]
		then 
			/usr/bin/kill `/usr/bin/cat /var/tmp/beaver.pid`
			/usr/bin/pkill -P `/usr/bin/cat /var/tmp/beaver.pid` beaver
			/usr/bin/rm -rf /var/tmp/beaver.pid
		fi
	;;
esac